SIMILARITY MEASURES FOR VECTORS

Euclidian Distance

In [1]:
#euclidean distance
from math import*
 
def euclidean_distance(x,y):
 
    return sqrt(sum(pow(a-b,2) for a, b in zip(x, y)))
 
print (euclidean_distance([0],[7]))

7.0


Manhattan Distance

In [4]:
#manhattan distance
from math import*
def manhattan_dist(x,y):
    return sum(abs(a-b) for a,b in zip(x,y))
print( manhattan_dist([1,2,3],[4,5,6]))

9


Minkowski Distance

In [44]:
#minkowski_distance

from math import*
from decimal import Decimal
def nth_root(value, n_root):
    root_value = 1/float(n_root)
    return round(Decimal(value) ** Decimal(root_value),3)
def minkowski_dist(x,y,P_value):
    return nth_root(sum(pow(abs(a-b),P_value) for a, b in zip(x,y)), P_value)
print(minkowski_dist([0,3,4,5],[7,6,3,-1],3))

 #p_value=1 : manhattan distance
 #p_value=2 : euclidean distance   
 #p_value=infinite : chebyshev diastance

8.373


In [46]:
import numpy as np
a=[1,2,3,6]
b=[4,5,6,7,8]
np.mean(a)


3.0

In [45]:
#standard correlation
#cosine similarity
import numpy as np
from math import*
def square_rooted(x):
    return round(sqrt(sum([a*a for a in x])),3)
def cos_sim(x,y):
    return round(np.dot(x,y) / float(square_rooted(x)*square_rooted(y)),3)
print(cos_sim([3, 35, 7, 2], [2, 54, 13, 15]))
    

0.977


Pearson correlation

In [1]:
#pearson correlation
import numpy as np
from math import*
def square_rooted(x):
    return round(sqrt(sum([a*a for a in x])),3)
def pearson_correlation(x,y):
    x_m =np.mean(x)
    y_m =np.mean(y)
    for i in range(len(x)):
        x[i]=x[i] - x_m
    for j in range(len(y)):
        y[j]=y[j] - y_m
    return round(np.dot(x,y) / float(square_rooted(x)*square_rooted(y)),3)
print(pearson_correlation([1, 1575451, 1562, 78], [2, 450819, 46, 80]))

1.0


Jaccard Similarity

In [22]:
#jaccard similarity
from math import*
def jaccard_similarity(x,y):
    intersection_cardinality = len(set.intersection(*[set(x),set(y)]))
    union_cardinality = len(set.union(*[set(x),set(y)]))
    return (intersection_cardinality/float(union_cardinality))
print(jaccard_similarity([0,1,2,5,6],[0,2,3,5,7,9]))

0.375


Dice's Coefficient

In [40]:
#dice's coefficient
from math import*
def dice_coefficient(x,y):
    intersection_cardinality = len(set.intersection(*[set(x),set(y)]))
    card_a = len(set(a))
    card_b = len(set(b))
    return (2*intersection_cardinality/float(card_a + card_b))
print(dice_coefficient([0,1,2,5,6],[0,2,3,5,7,9]))

0.6666666666666666


Canberra Coefficient

In [18]:
#canberra coefiicient

def canberra_coefficient(x,y):
    return round(sum(abs(a-b)/(abs(a) + abs(b)) for a,b in zip(x,y)), 3)
print(canberra_coefficient([0,1,2,3],[6,5,7,4]))

2.365


Overlap Coefficient

In [42]:
#overlap coefficient
from math import*
def overlap_coefficient(x,y):
    intersection_cardinality = len(set.intersection(*[set(x),set(y)]))
    card_a = len(set(a))
    card_b = len(set(b))
    s= min(card_a,card_b)
    return (intersection_cardinality/float(s))
print(overlap_coefficient([0,1,2,5,6],[0,2,3,5,7,9]))

0.75


Mahalanobis Distance


In [ ]:
#mahalanobis diastance

import numpy as np
from scipy.spatial.distance import cdist

x = np.array([[[1,2,3,4,5],
               [5,6,7,8,5],
               [5,6,7,8,5]],
              [[11,22,23,24,5],
               [25,26,27,28,5],
               [5,6,7,8,5]]])
i,j,k = x.shape

xx = x.reshape(i,j*k).T


y = np.array([[[31,32,33,34,5],
               [35,36,37,38,5],
               [5,6,7,8,5]],
              [[41,42,43,44,5],
               [45,46,47,48,5],
               [5,6,7,8,5]]])


yy = y.reshape(i,j*k).T

results =  cdist(xx,yy,'mahalanobis')
results = np.diag(results)
print( results)


In [4]:
#only using numpy
X = np.vstack([xx,yy])
V = np.cov(X.T)
VI = np.linalg.inv(V)
print (np.diag(np.sqrt(np.dot(np.dot((xx-yy),VI),(xx-yy).T))))

[2.28765854 2.75165028 2.75165028 2.75165028 0.         2.75165028
 2.75165028 2.75165028 2.75165028 0.         0.         0.
 0.         0.         0.        ]


Bray-Curtis distance

In [12]:
#bray - curtis distance

def braycurtis_distance(x,y):
    s1 = sum([abs((a+b)) for a,b in zip(x,y)])
    s2 = sum([abs((a-b)) for a,b in zip(x,y)])
    return round(s1/float(s2) ,3)
print( braycurtis_distance([0,3,4,5],[7,6,5,3]))
    

2.538


SIMILARITY MEASURE FOR STRINGS

Hamming Distance

In [11]:
#hamming distance- between the strings (dissimilarity of characters)

def hamming_distance(str1,str2):
    distance=0
    for i in range(len(str1)):
        if str1[i] != str2[i] :
            distance += 1
    return distance
print(hamming_distance('njhnkcnklncknknlaakvnvkvkhvkhlavklva','njhnkcnklncknknlajfhnvkvkhvkhlauhfva'))
        

6


Lee Distance

In [16]:
#lee distance for q-ary alphabet

def lee_distance(x,y,q):
    return sum([min(abs(a-b),q- abs(a-b)) for a,b in zip(x,y)])
print(lee_distance([1,2,3,4],[3,4,5,6],6))

8


Simple Matching Coefficient

In [17]:
#simple matching coefficient

def simple_matching_coeff(x,y):
    p,q,r,s = (0,0,0,0)
    for i in range(len(x)):
        if x[i] ==1 and y[i] ==1 :
            p += 1
        elif x[i] == 1 and y[i]==0:
            q += 1
        elif x[i] == 0 and y[i] == 1:
            r += 1
        else:
            s += 1
    return (p+s)/float(p+q+r+s)
print(simple_matching_coeff([1,1,1,1],[0,1,0,0]))

0.25


Levensthein Distance

In [12]:
#levensthein distance

import numpy as np

def levenshtein(seq1, seq2):  
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = matrix[x-1, y-1] 
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

print( levenshtein('awesome','handsome'))

[[0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 1. 1. 2. 3. 4. 5. 6. 7.]
 [2. 2. 2. 2. 3. 4. 5. 6. 7.]
 [3. 3. 3. 3. 3. 4. 5. 6. 6.]
 [4. 4. 4. 4. 4. 3. 4. 5. 6.]
 [5. 5. 5. 5. 5. 4. 3. 4. 5.]
 [6. 6. 6. 6. 6. 5. 4. 3. 4.]
 [7. 7. 7. 7. 7. 6. 5. 4. 3.]]
3.0
